apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-netpol-deploy-fail.fullname" . }}
  labels:
    {{- include "test-netpol-deploy-fail.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "test-netpol-deploy-fail.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test-netpol-deploy-fail.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /{{ if .Values.fail }}fail-probe{{ end }}
              port: http