{{ if .Values.netpolEnabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "test-netpol-deploy-fail.fullname" . }}-{{ .Values.netpolNameSuffix }}
  namespace: default
spec:
  podSelector:
    matchLabels:
      {{- include "test-netpol-deploy-fail.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/24
      ports:
        - protocol: TCP
          port: {{ .Values.netpolPort }}
{{ end }}